// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuyioczahgozvdbfodht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eWlvY3phaGdvenZkYmZvZGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTY4MjQsImV4cCI6MjA2NjQ5MjgyNH0.xl86ju_28dzeygKr6YFBZLHAXP8upCy9f1LbrikE7xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);